Homework1
made-ml-in-prod-2022/vlasdash pull request #1
Opened 2022-05-08 15:07 UTC by vlasdash

**Критерии**

- [X]  В описании к пулл реквесту описаны основные "архитектурные" и тактические решения - 1/1 балл

- [X] В пулл-реквесте проведена самооценка - 1/1 балл

- [ ] Выполнено EDA. Написать скрипт, который сгенерит отчет - 0/2 баллов

- [X] Написана функция для тренировки модели, вызов оформлен как утилита командной строки, записана в readme инструкцию по запуску - 3/3 балла

- [X] Написана функция predict, которая примет на вход артефакт/ы от обучения, тестовую выборку (без меток) и запишет предикт по заданному пути, инструкция по вызову записана в readme - 3/3 балла

- [X] Проект имеет модульную структуру, использовался cookiecutter-data-science - 2/2 балла

- [X] Использованы логгеры - 2/2 балла

- [X] Написаны тесты с помощью unittest на отдельные модули и на прогон обучения и predict - 3/3 балла

- [X] Для тестов генерируются синтетические данные, приближенные к реальным. Данные генерируются с помощью функции random - 2/2 балла

- [X] Обучение модели конфигурируется с помощью конфигов в yaml. Имеются две конфигурации для моделей RandomForestClassifier и SGDClassifier - 3/3 балла

- [X] Используются датаклассы для сущностей из конфига - 2/2 балла

- [X] Написан кастомный трансформер MinMaxScaler и протестирован - 3/3 балла 

- [X] В проекте зафиксированы все зависимости - 1/1 балл

- [ ] Настроен CI для прогона тестов, линтера - 0/3 балла

**Дополнительные баллы**

- [X] Используйте hydra для конфигурирования - 3/3 балла

- [ ] Использован Mlflow - 0/6 баллов

2022-05-12 19:41 UTC, SVizor42 commented on ml_project/src/train_pipeline.py
> +import sys
Не используется

2022-05-12 19:43 UTC, SVizor42 commented on ml_project/src/train_pipeline.py
> +def train_pipeline(training_pipeline_params: TrainingPipelineParams):
Return type?

2022-05-12 20:06 UTC, SVizor42 commented on ml_project/src/train_pipeline.py
> +    path_to_transformer = serialize_transformer(
Лучше сохранять весь пайплайн (трансформер + модель). Так тоже ок.

2022-05-12 20:31 UTC, SVizor42 commented on ml_project/src/predict_pipeline.py
> +import sys
Аналогично

2022-05-12 20:57 UTC, SVizor42 requested changes
1. Добавь пожалуйста docstrings.
2. Прогони код еще раз через flake или другой линтер.
3. Для логгеров также можно использовать отдельный конфиг (на будущее).

2022-05-12 21:04 UTC, SVizor42 commented on ml_project/README.md
> +        │
entities?

2022-05-20 20:53 UTC, vlasdash commented
1. Добавила в функции docstrings
2. Прогнала код через flake8
3. Удалила импорт неиспользуемых модулей
4. Добавила return type в функцию train_pipeline

2022-05-20 21:30 UTC, SVizor42 approved these changes
29 баллов.
Все хорошо. Можешь мерджить

2022-05-21 18:22 UTC, merged